#!/opt/local/bin/ruby -w
# git clone http://github.com/jjl/get_iplayer.git ~/Workspace/bin/get_iplayer/get_iplayer
# curl http://ftp.twaren.net/Unix/NonGNU/flvstreamer/macosx/flvstreamer_macosx_intel_32bit_latest --output ~/Workspace/bin/flvstreamer
# chmod 755 ~/Workspace/bin/flvstreamer

GET_IPLAYER = "~/Workspace/bin/get_iplayer/get_iplayer"
IPLAYER_CACHE = "~/.get_iplayer/radio.cache"
FLVSTREAMER = "~/Workspace/bin/flvstreamer"
DOWNLOAD_PATH = "~/Music/BBC"

puts ""
puts "*********** to refresh the list"
puts "#{GET_IPLAYER} --refresh --type=radio"
puts ""
puts "to find a program pid"
puts "cat ~/.get_iplayer/radio.cache | grep '[SHOW NAME]' | awk 'BEGIN {FS=\"|\"}{ print $4, \" \",  $3, \" \", $11 }'"
puts ""
puts "to download the program"
puts "#{GET_IPLAYER} --type=radio --amode=flashaac --pid [PID] --flvstreamer #{FLVSTREAMER}  --output #{DOWNLOAD_PATH}"

puts ""
puts "refreshing radio programs"
`#{GET_IPLAYER} --refresh --type=radio`

["Pete Tong", "Annie Mac", "Judge Jules", "BBC Radio 1's Essential Mix", "Friday Floor Fillers", "Dave Pearce Dance Anthems"].each do |name|
  show = `cat #{IPLAYER_CACHE} | grep "#{name}"`

  parts = show.split('|')
  # puts [parts[0], parts[2], parts[3], parts[5], parts[10]].join(', ')
  puts "echo '#{parts[5]} - #{parts[2]}'"

  `cd #{DOWNLOAD_PATH} && #{GET_IPLAYER} --type=radio --amode=flashaac --get #{parts[0]} --flvstreamer #{FLVSTREAMER}  --output #{DOWNLOAD_PATH}`
  
end  
